import type { CardTemplate } from '../../types';

export const confettiCelebrationTemplate: CardTemplate = {
  id: 'confetti-celebration',
  name: 'Confetti Celebration',
  category: 'birthday',
  tags: ['birthday', 'fun', 'colorful', 'party', 'confetti', 'celebration', 'vibrant', 'cute'],
  isPremium: false,
  isTrending: true,
  background: {
    type: 'gradient',
    value: ['#FEFCE8', '#FEF9C3', '#FEF3C7'],
    gradientStart: { x: 0, y: 0 },
    gradientEnd: { x: 0.5, y: 1 },
  },
  colors: { primary: '#F59E0B', secondary: '#EF4444', text: '#1C1917', accent: '#8B5CF6' },
  fonts: { heading: 'System', body: 'System' },
  placeholders: {
    recipientName: 'Riya',
    message: 'Blow the candles, make a wish, and let the magic begin!',
    senderName: 'Your Party Crew',
  },
  decorations: ['icon:balloon', 'icon:party-popper', 'icon:party-popper'],
  layout: 'portrait',
  elements: [
    { id: 'cc-1', type: 'sticker', content: 'icon:balloon', x: 15, y: 12, width: 32, height: 32, rotation: -12, opacity: 0.85, zIndex: 1, visible: true, fontSize: 26 },
    { id: 'cc-2', type: 'sticker', content: 'icon:party-popper', x: 285, y: 10, width: 32, height: 32, rotation: 10, opacity: 0.85, zIndex: 1, visible: true, fontSize: 26 },
    { id: 'cc-3', type: 'sticker', content: 'icon:party-popper', x: 60, y: 30, width: 20, height: 20, rotation: -18, opacity: 0.5, zIndex: 1, visible: true, fontSize: 15 },
    { id: 'cc-4', type: 'sticker', content: 'icon:sparkles', x: 260, y: 42, width: 18, height: 18, rotation: 0, opacity: 0.4, zIndex: 1, visible: true, fontSize: 13 },
    { id: 'cc-5', type: 'sticker', content: 'icon:gift', x: 30, y: 55, width: 16, height: 16, rotation: 5, opacity: 0.35, zIndex: 1, visible: true, fontSize: 12 },
    { id: 'cc-6', type: 'text', content: 'It\'s Your\nBirthday!', x: 25, y: 75, width: 290, height: 95, rotation: 0, opacity: 1, zIndex: 2, visible: true, fontSize: 38, fontWeight: '800', color: '#DC2626', textAlign: 'center', lineHeight: 48 },
    { id: 'cc-7', type: 'text', content: '{{recipientName}}', x: 20, y: 185, width: 300, height: 50, rotation: 0, opacity: 1, zIndex: 3, visible: true, fontSize: 42, fontWeight: '800', color: '#1C1917', textAlign: 'center', isPlaceholder: true, placeholderKey: 'recipientName' },
    { id: 'cc-8', type: 'sticker', content: 'icon:cake', x: 98, y: 248, width: 48, height: 48, rotation: 0, opacity: 1, zIndex: 2, visible: true, fontSize: 40 },
    { id: 'cc-9', type: 'sticker', content: 'icon:gift', x: 160, y: 252, width: 42, height: 42, rotation: -5, opacity: 0.9, zIndex: 2, visible: true, fontSize: 35 },
    { id: 'cc-10', type: 'sticker', content: 'icon:cake', x: 215, y: 250, width: 42, height: 42, rotation: 6, opacity: 0.9, zIndex: 2, visible: true, fontSize: 35 },
    { id: 'cc-11', type: 'text', content: '{{message}}', x: 35, y: 318, width: 270, height: 55, rotation: 0, opacity: 0.85, zIndex: 2, visible: true, fontSize: 14, fontWeight: '500', color: '#78350F', textAlign: 'center', lineHeight: 21, isPlaceholder: true, placeholderKey: 'message' },
    { id: 'cc-12', type: 'text', content: '— {{senderName}} —', x: 35, y: 400, width: 270, height: 25, rotation: 0, opacity: 0.6, zIndex: 2, visible: true, fontSize: 12, fontWeight: '600', color: '#B45309', textAlign: 'center', letterSpacing: 1, isPlaceholder: true, placeholderKey: 'senderName' },
    { id: 'cc-13', type: 'sticker', content: 'icon:balloon', x: 55, y: 435, width: 20, height: 20, rotation: 8, opacity: 0.35, zIndex: 1, visible: true, fontSize: 15 },
    { id: 'cc-14', type: 'sticker', content: 'icon:party-popper', x: 155, y: 445, width: 18, height: 18, rotation: 0, opacity: 0.35, zIndex: 1, visible: true, fontSize: 13 },
    { id: 'cc-15', type: 'sticker', content: 'icon:party-popper', x: 260, y: 438, width: 20, height: 20, rotation: -8, opacity: 0.35, zIndex: 1, visible: true, fontSize: 15 },
  ],
};
