import type { CardTemplate } from '../../types';

export const tropicalParadiseTemplate: CardTemplate = {
  id: 'tropical-paradise',
  name: 'Tropical Paradise',
  category: 'modern',
  tags: ['birthday', 'modern', 'tropical', 'summer', 'vibrant', 'fun', 'colorful', 'gradient'],
  isPremium: false,
  isTrending: true,
  background: {
    type: 'gradient',
    value: ['#FF6B6B', '#FF8E53', '#FEC89A'],
    gradientStart: { x: 0, y: 0 },
    gradientEnd: { x: 1, y: 1 },
  },
  colors: { primary: '#FFFFFF', secondary: '#FFF3E0', text: '#FFFFFF', accent: '#FFD93D' },
  fonts: { heading: 'System', body: 'System' },
  placeholders: {
    recipientName: 'Riya',
    message: 'Another year of sunshine, laughter, and incredible adventures awaits you!',
    senderName: 'With Sunny Vibes',
  },
  decorations: ['icon:tree-palm', 'icon:flower', 'icon:party-popper'],
  layout: 'portrait',
  elements: [
    { id: 'tp-1', type: 'sticker', content: 'icon:tree-palm', x: 15, y: 15, width: 35, height: 35, rotation: -10, opacity: 0.8, zIndex: 1, visible: true, fontSize: 28 },
    { id: 'tp-2', type: 'sticker', content: 'icon:flower', x: 280, y: 18, width: 35, height: 35, rotation: 15, opacity: 0.8, zIndex: 1, visible: true, fontSize: 28 },
    { id: 'tp-3', type: 'sticker', content: 'icon:leaf', x: 290, y: 60, width: 22, height: 22, rotation: 30, opacity: 0.4, zIndex: 1, visible: true, fontSize: 16 },
    { id: 'tp-4', type: 'text', content: 'Happy\nBirthday!', x: 25, y: 75, width: 290, height: 95, rotation: 0, opacity: 1, zIndex: 2, visible: true, fontSize: 38, fontWeight: '800', color: '#FFFFFF', textAlign: 'center', lineHeight: 48 },
    { id: 'tp-5', type: 'text', content: '{{recipientName}}', x: 20, y: 185, width: 300, height: 50, rotation: 0, opacity: 1, zIndex: 3, visible: true, fontSize: 42, fontWeight: '800', color: '#FFFFFF', textAlign: 'center', isPlaceholder: true, placeholderKey: 'recipientName' },
    { id: 'tp-6', type: 'sticker', content: 'icon:party-popper', x: 75, y: 250, width: 42, height: 42, rotation: -10, opacity: 0.9, zIndex: 2, visible: true, fontSize: 35 },
    { id: 'tp-7', type: 'sticker', content: 'icon:party-popper', x: 155, y: 245, width: 48, height: 48, rotation: 0, opacity: 1, zIndex: 2, visible: true, fontSize: 40 },
    { id: 'tp-8', type: 'sticker', content: 'icon:party-popper', x: 225, y: 250, width: 42, height: 42, rotation: 12, opacity: 0.9, zIndex: 2, visible: true, fontSize: 35 },
    { id: 'tp-9', type: 'text', content: '{{message}}', x: 35, y: 320, width: 270, height: 55, rotation: 0, opacity: 0.92, zIndex: 2, visible: true, fontSize: 14, fontWeight: '500', color: '#FFFFFF', textAlign: 'center', lineHeight: 21, isPlaceholder: true, placeholderKey: 'message' },
    { id: 'tp-10', type: 'text', content: '— {{senderName}} —', x: 35, y: 405, width: 270, height: 25, rotation: 0, opacity: 0.7, zIndex: 2, visible: true, fontSize: 13, fontWeight: '600', color: '#FFFFFF', textAlign: 'center', isPlaceholder: true, placeholderKey: 'senderName' },
    { id: 'tp-11', type: 'sticker', content: 'icon:flower', x: 60, y: 440, width: 20, height: 20, rotation: -10, opacity: 0.45, zIndex: 1, visible: true, fontSize: 14 },
    { id: 'tp-12', type: 'sticker', content: 'icon:sun', x: 160, y: 445, width: 22, height: 22, rotation: 0, opacity: 0.4, zIndex: 1, visible: true, fontSize: 16 },
    { id: 'tp-13', type: 'sticker', content: 'icon:flower', x: 255, y: 440, width: 20, height: 20, rotation: 10, opacity: 0.45, zIndex: 1, visible: true, fontSize: 14 },
  ],
};
