import type { CardTemplate } from '../../types';

export const vintageRoseTemplate: CardTemplate = {
  id: 'vintage-rose',
  name: 'Vintage Rose',
  category: 'floral',
  tags: ['birthday', 'floral', 'vintage', 'elegant', 'romantic', 'rose', 'premium', 'feminine'],
  isPremium: true,
  isTrending: false,
  background: {
    type: 'gradient',
    value: ['#FDF2F8', '#FECDD3', '#FFF1F2'],
    gradientStart: { x: 0, y: 0 },
    gradientEnd: { x: 0.5, y: 1 },
  },
  colors: { primary: '#BE185D', secondary: '#DB2777', text: '#831843', accent: '#F472B6' },
  fonts: { heading: 'System', body: 'System' },
  placeholders: {
    recipientName: 'Riya',
    message: 'Like a rose in bloom, you make this world more beautiful every day',
    senderName: 'Forever Yours',
  },
  decorations: ['icon:flower2', 'icon:flower', 'icon:heart'],
  layout: 'portrait',
  elements: [
    { id: 'vr-1', type: 'sticker', content: 'icon:flower2', x: 20, y: 15, width: 32, height: 32, rotation: -15, opacity: 0.7, zIndex: 1, visible: true, fontSize: 25 },
    { id: 'vr-2', type: 'sticker', content: 'icon:flower', x: 280, y: 12, width: 32, height: 32, rotation: 12, opacity: 0.6, zIndex: 1, visible: true, fontSize: 24 },
    { id: 'vr-3', type: 'sticker', content: 'icon:flower2', x: 50, y: 48, width: 18, height: 18, rotation: -5, opacity: 0.35, zIndex: 1, visible: true, fontSize: 13 },
    { id: 'vr-4', type: 'sticker', content: 'icon:flower2', x: 268, y: 52, width: 18, height: 18, rotation: 8, opacity: 0.35, zIndex: 1, visible: true, fontSize: 13 },
    { id: 'vr-5', type: 'text', content: 'Happy', x: 30, y: 75, width: 280, height: 38, rotation: 0, opacity: 0.65, zIndex: 2, visible: true, fontSize: 20, fontWeight: '500', color: '#DB2777', textAlign: 'center', letterSpacing: 8 },
    { id: 'vr-6', type: 'text', content: 'Birthday', x: 30, y: 108, width: 280, height: 52, rotation: 0, opacity: 1, zIndex: 2, visible: true, fontSize: 42, fontWeight: '800', color: '#BE185D', textAlign: 'center' },
    { id: 'vr-7', type: 'text', content: '{{recipientName}}', x: 20, y: 175, width: 300, height: 48, rotation: 0, opacity: 1, zIndex: 3, visible: true, fontSize: 36, fontWeight: '800', color: '#9F1239', textAlign: 'center', isPlaceholder: true, placeholderKey: 'recipientName' },
    { id: 'vr-8', type: 'sticker', content: 'icon:flower2', x: 110, y: 240, width: 44, height: 44, rotation: -8, opacity: 0.9, zIndex: 2, visible: true, fontSize: 36 },
    { id: 'vr-9', type: 'sticker', content: 'icon:flower', x: 165, y: 238, width: 44, height: 44, rotation: 0, opacity: 0.9, zIndex: 2, visible: true, fontSize: 36 },
    { id: 'vr-10', type: 'sticker', content: 'icon:flower2', x: 218, y: 240, width: 44, height: 44, rotation: 8, opacity: 0.9, zIndex: 2, visible: true, fontSize: 36 },
    { id: 'vr-11', type: 'text', content: '{{message}}', x: 38, y: 310, width: 264, height: 60, rotation: 0, opacity: 0.85, zIndex: 2, visible: true, fontSize: 14, fontWeight: '400', color: '#9F1239', textAlign: 'center', lineHeight: 21, isPlaceholder: true, placeholderKey: 'message' },
    { id: 'vr-12', type: 'text', content: '— {{senderName}} —', x: 35, y: 400, width: 270, height: 25, rotation: 0, opacity: 0.6, zIndex: 2, visible: true, fontSize: 12, fontWeight: '600', color: '#DB2777', textAlign: 'center', letterSpacing: 2, isPlaceholder: true, placeholderKey: 'senderName' },
    { id: 'vr-13', type: 'sticker', content: 'icon:heart', x: 156, y: 438, width: 24, height: 24, rotation: 0, opacity: 0.4, zIndex: 1, visible: true, fontSize: 18 },
    { id: 'vr-14', type: 'sticker', content: 'icon:flower', x: 25, y: 430, width: 22, height: 22, rotation: -10, opacity: 0.25, zIndex: 1, visible: true, fontSize: 16 },
    { id: 'vr-15', type: 'sticker', content: 'icon:flower2', x: 290, y: 435, width: 22, height: 22, rotation: 10, opacity: 0.25, zIndex: 1, visible: true, fontSize: 16 },
  ],
};
