import {
  Award,
  Baby,
  Balloon,
  Bell,
  BellRing,
  Briefcase,
  Cake,
  Camera,
  Candy,
  Check,
  Circle,
  CircleDot,
  CloudSun,
  Coffee,
  Crown,
  Flower,
  Flower2,
  Gamepad2,
  Gift,
  Heart,
  HeartHandshake,
  Image,
  Laugh,
  Leaf,
  Lightbulb,
  Mail,
  MessageCircle,
  Mic,
  Moon,
  Music,
  Palette,
  PartyPopper,
  Rainbow,
  Gem,
  Rocket,
  Search,
  Share2,
  Sparkles,
  Star,
  Sun,
  Target,
  TreePalm,
  Trophy,
  Users,
  Utensils,
  Wine,
  Zap,
  type LucideIcon,
} from 'lucide-react-native';

/** Maps icon keys (used in card stickers & decoration picker) to Lucide components. */
export const LUCIDE_ICON_MAP: Record<string, LucideIcon> = {
  award: Award,
  baby: Baby,
  balloon: Balloon,
  bell: Bell,
  'bell-ring': BellRing,
  briefcase: Briefcase,
  cake: Cake,
  camera: Camera,
  candy: Candy,
  check: Check,
  circle: Circle,
  'circle-dot': CircleDot,
  'cloud-sun': CloudSun,
  coffee: Coffee,
  crown: Crown,
  flower: Flower,
  flower2: Flower2,
  gamepad: Gamepad2,
  gift: Gift,
  heart: Heart,
  'heart-handshake': HeartHandshake,
  image: Image,
  laugh: Laugh,
  leaf: Leaf,
  lightbulb: Lightbulb,
  mail: Mail,
  'message-circle': MessageCircle,
  mic: Mic,
  moon: Moon,
  music: Music,
  palette: Palette,
  'party-popper': PartyPopper,
  rainbow: Rainbow,
  gem: Gem,
  rocket: Rocket,
  search: Search,
  share: Share2,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  target: Target,
  'tree-palm': TreePalm,
  trophy: Trophy,
  users: Users,
  utensils: Utensils,
  wine: Wine,
  zap: Zap,
};

export function getLucideIcon(name: string): LucideIcon | null {
  return LUCIDE_ICON_MAP[name] ?? null;
}

export function isIconStickerContent(content: string): boolean {
  return content.startsWith('icon:');
}

export function parseIconStickerContent(content: string): string {
  return content.slice(5);
}

/** Legacy emoji → icon key for card template migration. */
export const EMOJI_TO_ICON: Record<string, string> = {
  '🎈': 'balloon',
  '🎊': 'party-popper',
  '🎉': 'party-popper',
  '✨': 'sparkles',
  '🎀': 'gift',
  '🎂': 'cake',
  '🎁': 'gift',
  '🧁': 'cake',
  '💖': 'heart',
  '❤️': 'heart',
  '💕': 'heart',
  '💗': 'heart',
  '💝': 'gift',
  '💘': 'heart',
  '💓': 'heart',
  '🥰': 'heart',
  '😍': 'heart',
  '⭐': 'star',
  '🥳': 'party-popper',
  '👑': 'crown',
  '💫': 'sparkles',
  '🎵': 'music',
  '🪩': 'sparkles',
  '🎆': 'sparkles',
  '🎇': 'sparkles',
  '🍾': 'wine',
  '🥂': 'wine',
  '🎪': 'party-popper',
  '⚡': 'zap',
  '🌸': 'flower',
  '🌹': 'flower2',
  '🌺': 'flower',
  '💐': 'flower2',
  '🌷': 'flower2',
  '🌻': 'flower',
  '🌼': 'flower',
  '🍀': 'leaf',
  '🌿': 'leaf',
  '🦋': 'sparkles',
  '🕊️': 'sparkles',
  '🌈': 'rainbow',
  '🍰': 'cake',
  '🍩': 'candy',
  '🍪': 'candy',
  '🍫': 'candy',
  '🍭': 'candy',
  '🍬': 'candy',
  '🕯️': 'sparkles',
  '🥧': 'cake',
  '🎃': 'sparkles',
  '🍦': 'candy',
  '🎭': 'sparkles',
  '🎨': 'palette',
  '🎤': 'mic',
  '🎸': 'music',
  '🎯': 'target',
  '🎮': 'gamepad',
  '🏆': 'trophy',
  '🎲': 'gamepad',
  '🧸': 'baby',
  '🪄': 'sparkles',
  '🔮': 'sparkles',
  '🌴': 'tree-palm',
  '🍃': 'leaf',
  '☀️': 'sun',
  '🌙': 'moon',
  '🪐': 'moon',
  '◆': 'circle',
  '◇': 'circle-dot',
  '✦': 'sparkles',
  '📸': 'camera',
  '💜': 'heart',
  '🤍': 'circle',
  '💛': 'heart',
  '💞': 'heart',
  '🏡': 'heart',
};

export function emojiToIconKey(emoji: string): string {
  return EMOJI_TO_ICON[emoji] ?? 'sparkles';
}
